#### 1.) Hello world

With Julia installed and added to your path this script can be run by ** julia hello_world.jl ** , it can also be run from REPL by typing ** include("hello_world.jl") **, that will evaluate all valid expressions in that file and return the last output.

In [1]:
println("hello world")

hello world


#### 2) Simple Functions

In [2]:
# function to caculate the volume of sphere
function sphere_vol(r)
    # so either "pi" or the symbol π can be used
    return 4/3*pi*r^3
end


# function can also be defined more succinctly
quadratic(a,sqr_term,b)=(-b+sqr_term)/2a


function quadratic2(a::Float64,b::Float64,c::Float64)
    sqr_term=sqrt(b^2-4*a*c)
    r1=quadratic(a,sqr_term,b)
    r2=quadratic(a,-sqr_term,b)
    return r1,r2
end

quadratic2 (generic function with 1 method)

In [8]:
using Printf
vol=sphere_vol(3)
Printf.@printf "volume = %0.3f\n" vol 


quad1,quad2=quadratic2(2.0,-2.0,-12.0)
println("result 1:",quad1)
println("result 2:",quad2)

volume = 113.097
result 1:3.0
result 2:-2.0


#### 3) Strings Basics

In [11]:
s1 = "The quick brown fox jumps over the lazy dog α,β,γ"
println(s1)

println("This")
println("and")
print("That \n")


a="welcome"
b="julia"
println("$a to $b")
println("1 + 2 = $(1 + 2)")

s2 = "this" * " and" * " that"
println(s2)
#> this and that

# as well as the string function
s3 = string("this", " and", " that")
println(s3)

The quick brown fox jumps over the lazy dog α,β,γ
This
and
That 
welcome to julia
1 + 2 = 3
this and that
this and that


#### 4)String: Converting and formatting

In [12]:
# strings can be converted using float and int:
e_str1 = "2.718"
e = float(e_str1)

println(5e)
num_15 = parse(Int, "15")
println(3num_15)

13.59


┌ Warning: `float(x::AbstractString)` is deprecated, use `parse(Float64, x)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0


45


In [14]:
Printf.@printf "e=%0.2f\n" e
e_str2 =Printf.@sprintf("%0.3f", e)
println("e_str1 == e_str2: $(e_str1 == e_str2)")


Printf.@printf "fix trailing precision: %0.3f\n" float(pi)
#> fix trailing precision: 3.142
Printf.@printf "scientific form: %0.6e\n" 1000pi
#> scientific form: 3.141593e+03
# g is not implemented yet
Printf.@printf "a character: %c\n" 'α'
#> a character: α
Printf.@printf "a string: %s\n" "look I'm a string!"
#> a string: look I'm a string!
Printf.@printf "right justify a string: %50s\n" "width 50, text right justified!"
#> right justify a string:                    width 50, text right justified!
Printf.@printf "a pointer: %p\n" 100000000
#> a pointer: 0x0000000005f5e100
Printf.@printf "print a integer: %d\n" 1e10

e=2.72
e_str1 == e_str2: true
fix trailing precision: 3.142
scientific form: 3.141593e+03
a character: α
a string: look I'm a string!
right justify a string:                    width 50, text right justified!
a pointer: 0x0000000005f5e100
print a integer: 10000000000


#### 5)String Manipulations

In [25]:
s1 = "The quick brown fox jumps over the lazy dog α,β,γ"
i=findfirst(s1,'b')
println(i)

r=search(s1,"brown")
println(r)


# replace
r = replace(s1, "brown", "red")
show(r); println()


# search and replace can also take a regular expressions by preceding the string with 'r'
r=search(s1,r"b[\w]*n")
println(r)

# again with a regular expression
r = replace(s1, r"b[\w]*n", "red")
show(r); println()


# there are also functions for regular expressions that return RegexMatch types
# match scans left to right for the first match (specified starting index optional)
r = match(r"b[\w]*n", s1)
println(r)

11
11:15
"The quick red fox jumps over the lazy dog α,β,γ"
11:15
"The quick red fox jumps over the lazy dog α,β,γ"
RegexMatch(

┌ Warning: `findfirst(A, v)` is deprecated, use `something(findfirst(isequal(v), A), 0)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `search(s::AbstractString, t::AbstractString)` is deprecated, use `something(findfirst(t, s), 0:-1)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `search(s::AbstractString, r::Regex)` is deprecated, use `something(findfirst(r, s), 0:-1)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0


"brown")


In [34]:
r="hello "^3
show(r); println()

r=strip("hello ")
show(r);println()

r = split("hello, there,bob", ',')
show(r); println() #> ["hello"," there","bob"]


r = split("hello, there,bob", [',', ' '], limit=0, keep=false)
show(r); println() #> ["hello","there","bob"]


r = join(collect(1:10), ", ")
println(r)

"hello hello hello "
"hello"
SubString{String}["hello", " there", "bob"]
SubString{String}["hello", "there", "bob"]
1, 2, 3, 4, 5, 6, 7, 8, 9, 10


#### 6) Arrays

In [41]:
function printsum(a)
    println(summary(a),": ",repr(a))
end

a1=[1,2,3]
printsum(a1)

a2=collect(1:20)
printsum(a2)

a3=[2^i for i=1:10]
printsum(a3)

push!(a1,4)
printsum(a1)

append!(a1,[5,6,7])

3-element Array{Int64,1}: [1, 2, 3]
20-element Array{Int64,1}: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
10-element Array{Int64,1}: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
4-element Array{Int64,1}: [1, 2, 3, 4]


7-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7

push! :similiar append function

In [42]:
a4=repeat(a1,inner=[2],outer=[1])
printsum(a4)

14-element Array{Int64,1}: [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]


┌ Warning: Deprecated syntax ``?` used as an identifier`.
└ @ nothing none:1


#### 7) Error Handing

In [44]:
a=[]
try
    push!(a,1)
catch err
    showerror(TDOUT, err, backtrace());println()
end
println("Contuning after error")


Contuning after error


#### 8) Loops and Map

In [54]:
for i=1:5
    print(i," ")
end
println()


a1=[1,2,3,4]
for i in a1
    print(i,", ")
end
println()


a2=collect(1:20)
for i in a2
    if i%2 !=0
        continue
    end
    print(i,", ")
    if i>=8
        break
    end
end
println()

1 2 3 4 5 


┌ Warning: Deprecated syntax `implicit assignment to global variable `i``.
│ Use `global i` instead.
└ @ nothing none:0
┌ Warning: Loop variable `i` overwrites a variable in an enclosing scope. In the future the variable will be local to the loop instead.
└ @ nothing none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `i``.
│ Use `global i` instead.
└ @ nothing none:0
┌ Warning: Loop variable `i` overwrites a variable in an enclosing scope. In the future the variable will be local to the loop instead.
└ @ nothing none:0


1, 2, 3, 4, 
2, 4, 6, 8, 


┌ Warning: Deprecated syntax `implicit assignment to global variable `i``.
│ Use `global i` instead.
└ @ nothing none:0
┌ Warning: Loop variable `i` overwrites a variable in an enclosing scope. In the future the variable will be local to the loop instead.
└ @ nothing none:0


In [58]:
d1=Dict(1=>"one",2=>"two",3=>"three")
for k in sort(collect(keys(d1)))
    print(k, ": ", d1[k], ", ")
end
println()


a4 = map((x) -> x^2, [1, 2, 3, 7])
print(a4) #> [1, 4, 9, 49]

1: one, 2: two, 3: three, 
[1, 4, 9, 49]

┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1


#### 9)Types
Types are a key way of structuring data within Julia.

In [64]:
type Person
    name::AbstractString
    male::Bool
    age::Float64
    children::Int
end

p=Person("Julia",false,4,0)
println(summary(p),":",repr(p))



people = Person[]
push!(people, Person("Steve", true, 42, 0))
push!(people, Person("Jade", false, 17, 3))
printsum(people)

Person:Person("Julia", false, 4.0, 0)


┌ Warning: Deprecated syntax `type` at In[64]:1.
│ Use `mutable struct` instead.
└ @ nothing In[64]:1


2-element Array{Person,1}: Person[Person("Steve", true, 42.0, 0), Person("Jade", false, 17.0, 3)]


┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1
┌ Warning: Deprecated syntax `type`.
│ Use `mutable struct` instead.
└ @ nothing none:1


In [65]:
type Family
    name::AbstractString
    members::Array{AbstractString,1}
    extended::Bool
    
    # constructor that takes one argument and generates a default
    # for the other two values
    Family(name::AbstractString)=new(name,AbstractString[],false)
    
    # constructor that takes two arguements and infers the third
    Family(name::AbstractString, members) = new(name, members, length(members) > 3)
end


fam1 = Family("blogs")
println(fam1)
#> Family("blogs",AbstractString[],false)
fam2 = Family("jones", ["anna", "bob", "charlie", "dick"])
println(fam2)

┌ Warning: Deprecated syntax `type` at In[65]:1.
│ Use `mutable struct` instead.
└ @ nothing In[65]:1


Family("blogs", AbstractString[], false)
Family("jones", AbstractString["anna", "bob", "charlie", "dick"], true)
